name: build

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build-mac:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 3.1
    - name: Build project
      run: dotnet publish -p:PublishSingleFile=true --no-self-contained -r osx-x64
    - uses: actions/upload-artifact@v3
      with:
        name: SCR-Random-Number-macOS
        path: SCR-Random-Number/bin/Debug/netcoreapp3.1/osx-x64/publish/SCR-Number-Generator
  build-win:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 3.1
    - name: Build project
      run: dotnet publish -p:PublishSingleFile=true --no-self-contained -r win10-x64
    - uses: actions/upload-artifact@v3
      with:
        name: SCR-Random-Number-Windows
        path: SCR-Random-Number/bin/Debug/netcoreapp3.1/win10-x64/publish/SCR-Number-Generator.exe